using ICities;
using CitiesHarmony.API;
using ColossalFramework.UI;
using UnityEngine.SceneManagement;

namespace BetterRoadToolbar
{
    public class Mod : LoadingExtensionBase, IUserMod
    {
        public string Name => "Better Road Toolbar";
        public string Description => "Adds more tabs in the Roads toolbar and changes sort order to make finding the right road that little bit easier.";

        public void OnEnabled()
        {
            HarmonyHelper.DoOnHarmonyReady(() => Patcher.PatchAll());
        }

        public void OnDisabled()
        {
            if (HarmonyHelper.IsHarmonyInstalled) Patcher.UnpatchAll();
        }

        public override void OnLevelLoaded(LoadMode mode)
        {
            if (EditableConfig == CurrentConfig)
            {
                EditableConfig = new Config(); //any changes made from now on will require a restart
            }
        }

        public void OnSettingsUI(UIHelperBase helper)
        {
            helper.AddSpace(16);
            var extractTransportModesCheckbox = (UICheckBox)helper.AddCheckbox("Extract Bus/Tram/Bike/Trolleybus/Monorail roads into separate tabs",
                EditableConfig.CreateTabsForTransportModes,
                (isChecked) => EditableConfig.Update(createTabsForTransportModes : isChecked));

            var useStandardSortingCheckbox = (UICheckBox)helper.AddCheckbox("Use default game sort order for roads", 
                EditableConfig.UseStandardSortOrder,
                (isChecked) => EditableConfig.Update(useStandardSortOrder : isChecked));

            var ignoreCustomTabsCheckbox = (UICheckBox)helper.AddCheckbox("Keep custom road tabs generated by other mods or DLCs",
                EditableConfig.IgnoreCustomTabs,
                (isChecked) => EditableConfig.Update(ignoreCustomTabs : isChecked));

            helper.AddSpace(16);
            helper.AddButton("Reset to default", 
                () =>
                {
                    // This not only updates the config, but also updates the checkboxes.
                    extractTransportModesCheckbox.isChecked = true;
                    useStandardSortingCheckbox.isChecked = false;
                    ignoreCustomTabsCheckbox.isChecked = true;
                });

            helper.AddSpace(16);

            if (CurrentConfig != EditableConfig || !IsMainMenu())
            {
                helper.AddGroup("Note: Settings changes will take effect after restarting the game.");
            }
        }

        public static bool IsMainMenu()
        {
            return SceneManager.GetActiveScene().name == "MainMenu";
        }

        public static bool IsInGame()
        {
            return SceneManager.GetActiveScene().name == "Game";
        }

        public static string Identifier = "WQ.BRT/";

        public static Config CurrentConfig = new Config();
        public static Config EditableConfig = CurrentConfig;
    }
}
